//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongNgheWeb_3_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Lession
    {
        public int ID { get; set; }
        public string LessionName { get; set; }
        public string URLLession { get; set; }
        public Nullable<double> TotalTime { get; set; }
        public Nullable<int> CourseID { get; set; }
    
        public virtual tbl_Course tbl_Course { get; set; }
    }
}
