//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongNgheWeb_3_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Position
    {
        public tbl_Position()
        {
            this.tbl_User = new HashSet<tbl_User>();
        }
    
        public int ID { get; set; }
        public string PositionName { get; set; }
    
        public virtual ICollection<tbl_User> tbl_User { get; set; }
    }
}
